# Generated by Django 4.1.4 on 2023-01-01 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djpaddle", "0005_alter_subscription_next_bill_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="cancellation_effective_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
